/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Motor;

/**
 *
 * @author DrGreend
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPaneMotor = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtRpm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtRpmMax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtCombus = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BtnInserir = new javax.swing.JButton();
        TxtLimpar = new javax.swing.JButton();
        BtnCons2 = new javax.swing.JButton();
        BtnCons3 = new javax.swing.JButton();
        BtnCons4 = new javax.swing.JButton();
        BtnCons6 = new javax.swing.JButton();
        BtnCons8 = new javax.swing.JButton();
        BtnCons7 = new javax.swing.JButton();
        BtnCons9 = new javax.swing.JButton();
        BtnCons5 = new javax.swing.JButton();
        BtnCons10 = new javax.swing.JButton();
        BtnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPaneMotor.setName(""); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Marca");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        TxtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 11, 204, -1));

        jLabel2.setText("Modelo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        TxtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtModeloActionPerformed(evt);
            }
        });
        jPanel1.add(TxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 37, 204, -1));

        jLabel3.setText("RPM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, -1, -1));

        TxtRpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRpmActionPerformed(evt);
            }
        });
        jPanel1.add(TxtRpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 68, 204, -1));

        jLabel4.setText("RPM Máximo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, -1, -1));

        TxtRpmMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRpmMaxActionPerformed(evt);
            }
        });
        jPanel1.add(TxtRpmMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 99, 204, -1));

        jLabel5.setText("Tipo Combustível");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, -1, -1));

        TxtCombus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCombusActionPerformed(evt);
            }
        });
        jPanel1.add(TxtCombus, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 125, 204, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnInserir.setText("Inserir");
        BtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserirActionPerformed(evt);
            }
        });
        jPanel2.add(BtnInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 91, -1));

        TxtLimpar.setText("Limpar!");
        TxtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLimparActionPerformed(evt);
            }
        });
        jPanel2.add(TxtLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        BtnCons2.setText("Construtor2");
        BtnCons2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCons2ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCons2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 56, -1, -1));

        BtnCons3.setText("Construtor3");
        BtnCons3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCons3ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCons3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 85, -1, -1));

        BtnCons4.setText("Construtor4");
        BtnCons4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCons4ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCons4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 114, -1, -1));

        BtnCons6.setText("Construtor6");
        BtnCons6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCons6ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCons6, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 27, -1, -1));

        BtnCons8.setText("Construtor8");
        BtnCons8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCons8ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCons8, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 85, -1, -1));

        BtnCons7.setText("Construtor7");
        BtnCons7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCons7ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCons7, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 56, -1, -1));

        BtnCons9.setText("Construtor9");
        BtnCons9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCons9ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCons9, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 114, -1, -1));

        BtnCons5.setText("Construtor5");
        BtnCons5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCons5ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCons5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 143, -1, -1));

        BtnCons10.setText("Construtor10");
        BtnCons10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCons10ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCons10, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 143, 100, -1));

        BtnImprimir.setText("Imprimir");
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(BtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 27, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 510, 182));

        JPaneMotor.addTab("Motor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPaneMotor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPaneMotor)
        );

        JPaneMotor.getAccessibleContext().setAccessibleName("Motor");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMarcaActionPerformed

    private void TxtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtModeloActionPerformed

    private void TxtRpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRpmActionPerformed

    private void TxtRpmMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRpmMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRpmMaxActionPerformed

    private void TxtCombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCombusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCombusActionPerformed

    private void BtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserirActionPerformed
        // TODO add your handling code here:
        int max = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantos motores deseja inserir?" , "Motor" ,JOptionPane.INFORMATION_MESSAGE));
        ArrayList<Motor> motor = new ArrayList<Motor>(max);
        Motor mt = new Motor();
        for(int i = 0; i < max; i++){
            mt.cadastrar(TxtMarca.getText(), TxtModelo.getText(), TxtCombus.getText(), Integer.parseInt(TxtRpm.getText()), Integer.parseInt(TxtRpmMax.getText()));
        }
        motor.add(mt);
    }//GEN-LAST:event_BtnInserirActionPerformed

    private void TxtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLimparActionPerformed
        // TODO add your handling code here:
        TxtMarca.setText("");
        TxtModelo.setText("");
        TxtCombus.setText("");
        TxtRpm.setText("");
        TxtRpmMax.setText("");
    }//GEN-LAST:event_TxtLimparActionPerformed

    private void BtnCons2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCons2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnCons2ActionPerformed

    private void BtnCons3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCons3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCons3ActionPerformed

    private void BtnCons4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCons4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCons4ActionPerformed

    private void BtnCons6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCons6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCons6ActionPerformed

    private void BtnCons8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCons8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCons8ActionPerformed

    private void BtnCons7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCons7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCons7ActionPerformed

    private void BtnCons9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCons9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCons9ActionPerformed

    private void BtnCons5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCons5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCons5ActionPerformed

    private void BtnCons10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCons10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCons10ActionPerformed

    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCons10;
    private javax.swing.JButton BtnCons2;
    private javax.swing.JButton BtnCons3;
    private javax.swing.JButton BtnCons4;
    private javax.swing.JButton BtnCons5;
    private javax.swing.JButton BtnCons6;
    private javax.swing.JButton BtnCons7;
    private javax.swing.JButton BtnCons8;
    private javax.swing.JButton BtnCons9;
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JButton BtnInserir;
    private javax.swing.JTabbedPane JPaneMotor;
    private javax.swing.JTextField TxtCombus;
    private javax.swing.JButton TxtLimpar;
    private javax.swing.JTextField TxtMarca;
    private javax.swing.JTextField TxtModelo;
    private javax.swing.JTextField TxtRpm;
    private javax.swing.JTextField TxtRpmMax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
